// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import type { Model } from "../types.ts";

export const ANTHROPIC_MODELS = {
    "claude-fable-5": {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        api: "anthropic-messages",
        provider: "anthropic",
        baseUrl: "https://api.anthropic.com",
        compat: { forceAdaptiveThinking: true },
        reasoning: true,
        thinkingLevelMap: { off: null, xhigh: "xhigh", max: "max" },
        input: ["text", "image"],
        cost: {
            input: 10,
            output: 50,
            cacheRead: 1,
            cacheWrite: 12.5,
        },
        contextWindow: 1000000,
        maxTokens: 128000,
    } satisfies Model<"anthropic-messages">,
    // ...
} as const;
